import { createContext, useContext, useState, useEffect } from 'react';

const FlashcardContext = createContext(undefined);

const DEFAULT_DECKS = [
  {
    id: 'deck-1',
    title: 'React Fundamentals',
    description: 'Core concepts, hooks, and patterns in React.',
    cards: [
      { id: 'c1', front: 'What is a Hook?', back: 'A special function that lets you "hook into" React features like state and lifecycle methods from a functional component.', status: 'new' },
      { id: 'c2', front: 'Difference between useEffect and useLayoutEffect?', back: 'useEffect runs asynchronously after paint. useLayoutEffect runs synchronously after DOM mutations but before paint.', status: 'new' },
      { id: 'c3', front: 'What is the Virtual DOM?', back: 'An in-memory representation of the real DOM elements generated by React components before any changes are applied to the actual page.', status: 'new' },
      { id: 'c4', front: 'Why do we need keys in lists?', back: 'Keys help React identify which items have changed, are added, or are removed, optimizing the rendering process.', status: 'new' }
    ],
    lastStudied: null
  }
];

export function FlashcardProvider({ children }) {
  const [decks, setDecks] = useState(() => {
    const saved = localStorage.getItem('eduwrap_flashcards');
    if (saved) {
      try {
        return JSON.parse(saved);
      } catch (e) {
        console.error('Failed to parse flashcards from local storage', e);
      }
    }
    return DEFAULT_DECKS;
  });

  const [activeDeckId, setActiveDeckId] = useState(null);

  useEffect(() => {
    localStorage.setItem('eduwrap_flashcards', JSON.stringify(decks));
  }, [decks]);

  const updateCardStatus = (deckId, cardId, status) => {
    setDecks(prev => prev.map(deck => {
      if (deck.id === deckId) {
        return {
          ...deck,
          cards: deck.cards.map(card => card.id === cardId ? { ...card, status } : card)
        };
      }
      return deck;
    }));
  };

  const updateDeckLastStudied = (deckId) => {
    setDecks(prev => prev.map(deck => 
      deck.id === deckId ? { ...deck, lastStudied: new Date().toISOString() } : deck
    ));
  };

  // Mock AI Generator
  const generateDeckFromPDF = async (pdfTitle) => {
    // In a real app, this would send PDF text to an AI API.
    // For now, we mock a delay and return a generated deck.
    return new Promise(resolve => {
      setTimeout(() => {
        const newDeck = {
          id: crypto.randomUUID(),
          title: `Generated: ${pdfTitle}`,
          description: `AI generated flashcards based on ${pdfTitle}`,
          cards: [
            { id: crypto.randomUUID(), front: 'What is the main topic of this PDF?', back: 'The PDF discusses advanced study techniques and memory retention.', status: 'new' },
            { id: crypto.randomUUID(), front: 'Define Spaced Repetition.', back: 'A learning technique that incorporates increasing intervals of time between subsequent review of previously learned material.', status: 'new' },
            { id: crypto.randomUUID(), front: 'What is active recall?', back: 'The process of actively stimulating memory during the learning process rather than passively reading.', status: 'new' }
          ],
          lastStudied: null
        };
        setDecks(prev => [newDeck, ...prev]);
        resolve(newDeck.id);
      }, 1500);
    });
  };

  return (
    <FlashcardContext.Provider
      value={{
        decks,
        activeDeckId,
        setActiveDeckId,
        updateCardStatus,
        updateDeckLastStudied,
        generateDeckFromPDF
      }}
    >
      {children}
    </FlashcardContext.Provider>
  );
}

export function useFlashcards() {
  const context = useContext(FlashcardContext);
  if (context === undefined) {
    throw new Error('useFlashcards must be used within a FlashcardProvider');
  }
  return context;
}
