import { createContext, useContext, useState, useEffect } from 'react';
import { getPDFText } from '../services/pdfService';
import { generateFlashcards } from '../services/questionGenerator';

const FlashcardContext = createContext(undefined);

const DEFAULT_DECKS = [
  {
    id: 'deck-1',
    title: 'React Fundamentals',
    description: 'Core concepts, hooks, and patterns in React.',
    cards: [
      { id: 'c1', front: 'What is a Hook?', back: 'A special function that lets you "hook into" React features like state and lifecycle methods from a functional component.', status: 'new' },
      { id: 'c2', front: 'Difference between useEffect and useLayoutEffect?', back: 'useEffect runs asynchronously after paint. useLayoutEffect runs synchronously after DOM mutations but before paint.', status: 'new' },
      { id: 'c3', front: 'What is the Virtual DOM?', back: 'An in-memory representation of the real DOM elements generated by React components before any changes are applied to the actual page.', status: 'new' },
      { id: 'c4', front: 'Why do we need keys in lists?', back: 'Keys help React identify which items have changed, are added, or are removed, optimizing the rendering process.', status: 'new' }
    ],
    lastStudied: null
  }
];

export function FlashcardProvider({ children }) {
  const [decks, setDecks] = useState(() => {
    const saved = localStorage.getItem('eduwrap_flashcards');
    if (saved) {
      try {
        return JSON.parse(saved);
      } catch (e) {
        console.error('Failed to parse flashcards from local storage', e);
      }
    }
    return DEFAULT_DECKS;
  });

  const [activeDeckId, setActiveDeckId] = useState(null);

  useEffect(() => {
    localStorage.setItem('eduwrap_flashcards', JSON.stringify(decks));
  }, [decks]);

  const updateCardStatus = (deckId, cardId, status) => {
    setDecks(prev => prev.map(deck => {
      if (deck.id === deckId) {
        return {
          ...deck,
          cards: deck.cards.map(card => card.id === cardId ? { ...card, status } : card)
        };
      }
      return deck;
    }));
  };

  const updateDeckLastStudied = (deckId) => {
    setDecks(prev => prev.map(deck =>
      deck.id === deckId ? { ...deck, lastStudied: new Date().toISOString() } : deck
    ));
  };

  const deleteDeck = (deckId) => {
    setDecks(prev => prev.filter(deck => deck.id !== deckId));
    if (activeDeckId === deckId) setActiveDeckId(null);
  };

  /**
   * Generate a flashcard deck from selected PDFs.
   * Uses the questionGenerator service for smart question extraction.
   */
  const generateDeck = async (selectedPdfIds, selectedPdfTitles, count) => {
    let combinedText = '';

    // 1. Fetch extracted text from IndexedDB for all selected PDFs
    for (const id of selectedPdfIds) {
      try {
        const text = await getPDFText(id);
        if (text) combinedText += text + '\n\n';
      } catch (err) {
        console.error("Failed to read text for pdf:", id, err);
      }
    }

    // 2. Generate cards using the smart question generator
    let cards = [];
    if (combinedText.trim().length > 50) {
      cards = generateFlashcards(combinedText, count);
    }

    // 3. If we couldn't generate enough, the PDF might be image-only or too sparse
    if (cards.length === 0) {
      console.warn("No text found in selected PDFs — generating fallback deck");
      cards = [{
        id: crypto.randomUUID(),
        front: 'No readable text found in the selected PDF(s).',
        back: 'This PDF may be image-based (scanned). Try selecting a different PDF with selectable text.',
        status: 'new',
      }];
    }

    const title = selectedPdfTitles.length > 1
      ? `Generated from ${selectedPdfTitles.length} PDFs`
      : `Generated: ${selectedPdfTitles[0] || 'Custom Deck'}`;

    const newDeck = {
      id: crypto.randomUUID(),
      title,
      description: `Smart flashcards extracted from your study materials.`,
      cards,
      lastStudied: null
    };

    setDecks(prev => [newDeck, ...prev]);
    return newDeck.id;
  };

  return (
    <FlashcardContext.Provider
      value={{
        decks,
        activeDeckId,
        setActiveDeckId,
        updateCardStatus,
        updateDeckLastStudied,
        generateDeck,
        deleteDeck
      }}
    >
      {children}
    </FlashcardContext.Provider>
  );
}

export function useFlashcards() {
  const context = useContext(FlashcardContext);
  if (context === undefined) {
    throw new Error('useFlashcards must be used within a FlashcardProvider');
  }
  return context;
}
